---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-svc
  name: {{ .Release.Name }}-svc
spec:
  ports:
{{ .Values.service.ports | toYaml | indent 4 }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
